alias ls='ls -lhGF --color'
alias clr='clear'
alias tree='tree -C'
alias python='python3'
alias pip='pip3'
alias ta='tmux attach -t'
alias tl='tmux ls'
alias tk='tmux kill-session -t'
alias vf='vifm .'
alias mkdir='mkdir -p'

